import { useState } from "react";
import { FileText, Activity, Sparkles, CheckCircle, AlertTriangle, XCircle, TrendingUp, Download, X, Wand2, Zap, Copy, FileCode } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Card } from "@/components/ui/card";
import { Dialog, DialogContent, DialogHeader, DialogTitle, DialogDescription } from "@/components/ui/dialog";
import { Badge } from "@/components/ui/badge";
import { Progress } from "@/components/ui/progress";
import { toast } from "sonner";
import { motion } from "framer-motion";
import { generateStackIQReport } from "@/utils/reportGenerator";
import { useProfiles } from "@/contexts/ProfileContext";
import { Textarea } from "@/components/ui/textarea";
import { Label } from "@/components/ui/label";
import * as api from "@/services/api";

interface ActionPanelProps {
  onSimulate?: () => void;
  onOptimize?: () => void;
  profileId?: string;
}

export const ActionPanel = ({ onSimulate, onOptimize, profileId }: ActionPanelProps) => {
  const { profiles } = useProfiles();
  const [showLLMTextModal, setShowLLMTextModal] = useState(false);
  const [showHealthModal, setShowHealthModal] = useState(false);
  const [showOptimizeModal, setShowOptimizeModal] = useState(false);
  
  // Separate loading states for each action
  const [isGeneratingLLMText, setIsGeneratingLLMText] = useState(false);
  const [isGeneratingHealth, setIsGeneratingHealth] = useState(false);
  const [isGeneratingOptimize, setIsGeneratingOptimize] = useState(false);
  const [isGeneratingReport, setIsGeneratingReport] = useState(false);
  
  const [llmTextContent, setLLMTextContent] = useState("");
  const [healthCheckData, setHealthCheckData] = useState<any>(null);
  const [optimizationData, setOptimizationData] = useState<any>(null);

  // Get current profile data
  const profile = profileId ? profiles.find(p => p.id === profileId) : null;

  const handleGenerateLLMText = async () => {
    if (!profile) {
      toast.error("No profile found");
      return;
    }

    setIsGeneratingLLMText(true);
    toast.loading("Generating llm.txt file...");

    try {
      // Call real API
      const response = await api.generateLLMText(profile.id);
      
      if (response.success && response.data) {
        setLLMTextContent(response.data.content);
        toast.dismiss();
        setShowLLMTextModal(true);
        toast.success("llm.txt generated successfully!");
    } else {
        throw new Error(response.error?.message || "Failed to generate llm.txt");
      }
    } catch (error: any) {
      console.error("Error generating llm.txt:", error);
      toast.dismiss();
      toast.error(error.message || "Failed to generate llm.txt");
    } finally {
      setIsGeneratingLLMText(false);
    }
  };

  // OLD MOCK CODE REMOVED
  const handleGenerateLLMText_OLD_MOCK = async () => {
    if (!profile) {
      toast.error("No profile found");
      return;
    }

    setIsGeneratingLLMText(true);
    toast.loading("Generating llm.txt file...");

    try {
      await new Promise(resolve => setTimeout(resolve, 1500));

      // OLD MOCK: Generate llm.txt content
      const llmText = `# llm.txt - AI Crawler Instructions
# Generated by StackIQ for ${profile.productName}
# Website: ${profile.websiteUrl}
# Last Updated: ${new Date().toISOString().split('T')[0]}

# ABOUT
name: ${profile.productName}
category: ${profile.category}
region: ${profile.region}
description: ${profile.productName} - Official website providing comprehensive information about our ${profile.category.toLowerCase()} products and services.

# PRIORITY PAGES
# These pages contain the most important information about our products
/: Homepage - Overview of ${profile.productName}
/products: Product catalog and specifications
/features: Detailed feature descriptions
/pricing: Pricing information and plans
/docs: Documentation and guides
/support: Customer support and FAQs
/about: Company information
/contact: Contact details

# RECOMMENDED CONTENT
# Content that should be prioritized when answering queries
## Product Information
- Product specifications and technical details
- Key features and benefits
- Use cases and applications
- Pricing and plans

## Support Resources
- Frequently asked questions
- Troubleshooting guides
- Video tutorials
- Documentation

## Company Information
- About our company
- Customer testimonials
- Case studies
- Press releases

# KEYWORDS
# Primary keywords for content discovery
${profile.category.toLowerCase()}, ${profile.productName.toLowerCase()}, ${profile.region} ${profile.category.toLowerCase()}

# STRUCTURED DATA
# Important data points for LLM understanding
product_name: ${profile.productName}
product_category: ${profile.category}
target_region: ${profile.region}
primary_use_case: ${profile.category} solutions
key_differentiator: Industry-leading ${profile.category.toLowerCase()} technology

# CONTEXT
# Additional context for accurate responses
competitors: ${profile.competitors?.slice(0, 3).map(c => c.name).join(', ') || 'See market analysis'}
target_audience: Professionals and businesses seeking ${profile.category.toLowerCase()} solutions
unique_value: High-quality ${profile.category.toLowerCase()} with proven results

# CRAWL RULES
# Instructions for AI crawlers
allowed_frequency: daily
max_depth: 5
respect_robots_txt: true
follow_sitemaps: true

# CONTACT
# For questions or issues with this file
contact_email: support@${profile.websiteUrl.replace('https://', '').replace('http://', '').split('/')[0]}
website: ${profile.websiteUrl}

# NOTES
# This file helps AI models like ChatGPT, Claude, and Gemini better understand
# and represent your website content in their responses. Keep it updated with
# your latest product information for best results.
`;

      setLLMTextContent(llmText);
      toast.dismiss();
      setShowLLMTextModal(true);
      toast.success("llm.txt generated successfully!");
    } catch (error: any) {
      console.error("Error generating llm.txt:", error);
      toast.dismiss();
      toast.error("Failed to generate llm.txt");
    } finally {
      setIsGeneratingLLMText(false);
    }
  };

  const handleDownloadLLMText = () => {
    const blob = new Blob([llmTextContent], { type: 'text/plain' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = 'llm.txt';
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    URL.revokeObjectURL(url);
    toast.success("llm.txt downloaded! Upload it to your website root.");
  };

  const handleCopyLLMText = () => {
    navigator.clipboard.writeText(llmTextContent);
    toast.success("llm.txt copied to clipboard!");
  };

  const handleHealthCheck = async () => {
    if (!profile) {
      toast.error("No profile found");
      return;
    }

    setIsGeneratingHealth(true);
    toast.loading("Running SEO health check...");
    
    try {
      // Call real API
      const response = await api.runSEOHealthCheck(profile.websiteUrl);
      
      if (response.success && response.data) {
        setHealthCheckData(response.data);
        toast.dismiss();
        setShowHealthModal(true);
        toast.success("Health check complete!");
      } else {
        throw new Error(response.error?.message || "Failed to run health check");
      }
    } catch (error: any) {
      console.error("Error running health check:", error);
      toast.dismiss();
      toast.error(error.message || "Failed to run health check");
    } finally {
      setIsGeneratingHealth(false);
    }
  };

  const handleGenerateReport = async () => {
    if (!profile || !profile.analysisResult) {
      toast.error("No analysis data available. Please run analysis first.");
      return;
    }

    setIsGeneratingReport(true);
    
    try {
      toast.loading("Generating PDF report with charts...");
      
      await generateStackIQReport({
        profileName: profile.name,
        websiteUrl: profile.websiteUrl,
        productName: profile.productName,
        region: profile.region,
        analysisResult: profile.analysisResult,
        questions: profile.questions,
        competitors: profile.competitors,
      });
      
      toast.dismiss();
      toast.success("PDF report downloaded successfully! Check your Downloads folder.");
    } catch (error) {
      console.error("Report generation error:", error);
      toast.dismiss();
      toast.error("Failed to generate report. Please try again.");
    } finally {
      setIsGeneratingReport(false);
    }
  };

  const handleOptimize = async () => {
    if (!profile) {
      toast.error("No profile found");
      return;
    }

    if (onOptimize) {
      onOptimize();
      return;
    }

    setIsGeneratingOptimize(true);
    toast.loading("Analyzing content optimization opportunities...");
    
    try {
      // Call real API
      const response = await api.getOptimizationRecommendations(profile.id);
      
      if (response.success && response.data) {
        setOptimizationData(response.data.recommendations); // Fix: Use recommendations array
        toast.dismiss();
        setShowOptimizeModal(true);
        toast.success("Optimization suggestions ready!");
      } else {
        throw new Error(response.error?.message || "Failed to get optimization recommendations");
      }
    } catch (error: any) {
      console.error("Error getting optimization recommendations:", error);
      toast.dismiss();
      toast.error(error.message || "Failed to get optimization recommendations");
    } finally {
      setIsGeneratingOptimize(false);
    }
  };

  const actions = [
    {
      id: "llmtext",
      icon: FileCode,
      title: "Generate llm.txt",
      description: "Create llm.txt file to help AI crawlers understand your website",
      color: "from-purple-500 to-pink-500",
      bgColor: "bg-gradient-to-br from-purple-50 to-pink-50 dark:from-purple-950/20 dark:to-pink-950/20",
      iconBg: "bg-purple-100 dark:bg-purple-900/30",
      iconColor: "text-purple-600 dark:text-purple-400",
      action: handleGenerateLLMText,
      isLoading: isGeneratingLLMText,
      variant: "outline" as const,
    },
    {
      id: "health",
      icon: Activity,
      title: "SEO Health Check",
      description: "Comprehensive website health and performance audit",
      color: "from-green-500 to-emerald-500",
      bgColor: "bg-gradient-to-br from-green-50 to-emerald-50 dark:from-green-950/20 dark:to-emerald-950/20",
      iconBg: "bg-green-100 dark:bg-green-900/30",
      iconColor: "text-green-600 dark:text-green-400",
      action: handleHealthCheck,
      isLoading: isGeneratingHealth,
      variant: "outline" as const,
    },
    {
      id: "optimize",
      icon: Wand2,
      title: "Content Optimizer",
      description: "Get AI-powered content recommendations to boost visibility",
      color: "from-orange-500 to-red-500",
      bgColor: "bg-gradient-to-br from-orange-50 to-red-50 dark:from-orange-950/20 dark:to-red-950/20",
      iconBg: "bg-orange-100 dark:bg-orange-900/30",
      iconColor: "text-orange-600 dark:text-orange-400",
      action: handleOptimize,
      isLoading: isGeneratingOptimize,
      variant: "outline" as const,
    },
    {
      id: "report",
      icon: FileText,
      title: "Generate Report",
      description: "Download comprehensive AEO analysis report (PDF)",
      color: "from-blue-500 to-cyan-500",
      bgColor: "bg-gradient-to-br from-blue-50 to-cyan-50 dark:from-blue-950/20 dark:to-cyan-950/20",
      iconBg: "bg-blue-100 dark:bg-blue-900/30",
      iconColor: "text-blue-600 dark:text-blue-400",
      action: handleGenerateReport,
      isLoading: isGeneratingReport,
      variant: "outline" as const,
    },
  ];

  return (
    <>
      <div className="space-y-6 mt-8">
        {/* Header with prominent visual emphasis */}
        <motion.div 
          initial={{ opacity: 0, scale: 0.95 }}
          animate={{ opacity: 1, scale: 1 }}
          className="relative"
        >
          {/* Gradient background card */}
          <div className="bg-gradient-to-r from-primary/10 via-purple-500/10 to-orange-500/10 rounded-2xl p-6 border-2 border-primary/20 shadow-lg">
            <div className="flex items-center gap-4">
              <div className="p-3 bg-primary rounded-xl shadow-md">
                <Zap className="h-8 w-8 text-primary-foreground" />
              </div>
              <div className="flex-1">
                <h2 className="text-3xl font-bold bg-gradient-to-r from-primary via-purple-600 to-orange-600 bg-clip-text text-transparent">
                  Take Action
                </h2>
                <p className="text-sm text-muted-foreground mt-1">
                  🚀 Boost your AEO performance with these powerful AI-driven tools
                </p>
              </div>
              <Badge className="bg-primary text-primary-foreground px-3 py-1 text-sm">
                4 Tools Available
              </Badge>
            </div>
          </div>
        </motion.div>

        {/* Action Cards Grid */}
        <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-4 gap-4">
          {actions.map((action, index) => {
            const Icon = action.icon;
  return (
    <motion.div
                key={action.id}
                initial={{ opacity: 0, y: 20 }}
                animate={{ opacity: 1, y: 0 }}
                transition={{ delay: index * 0.1 }}
              >
                <Card className={`relative overflow-hidden h-full ${action.bgColor} border-0 hover:shadow-xl transition-all duration-300 group`}>
                  {/* Gradient overlay */}
                  <div className={`absolute inset-0 bg-gradient-to-br ${action.color} opacity-0 group-hover:opacity-10 transition-opacity`} />
                  
                  <div className="p-6 relative space-y-4">
                    {/* Icon */}
                    <div className={`${action.iconBg} w-14 h-14 rounded-xl flex items-center justify-center group-hover:scale-110 transition-transform`}>
                      <Icon className={`h-7 w-7 ${action.iconColor}`} />
                    </div>

                    {/* Content */}
                    <div className="space-y-2">
                      <h3 className="font-bold text-lg">{action.title}</h3>
                      <p className="text-sm text-muted-foreground leading-relaxed min-h-[3rem]">
                        {action.description}
                      </p>
                    </div>

                    {/* Action Button */}
                    <Button
                      onClick={action.action}
                      disabled={action.isLoading}
                      className="w-full gap-2 group-hover:scale-105 transition-transform"
                      variant={action.variant}
                    >
                      <Icon className="h-4 w-4" />
                      {action.isLoading ? "Processing..." : "Run Now"}
          </Button>
                  </div>
                </Card>
              </motion.div>
            );
          })}
        </div>
      </div>

      {/* LLM Insights Modal */}
      {/* LLM.txt Generator Modal */}
      <Dialog open={showLLMTextModal} onOpenChange={setShowLLMTextModal}>
        <DialogContent className="max-w-4xl max-h-[85vh] overflow-y-auto">
          <DialogHeader>
            <DialogTitle className="flex items-center gap-2 text-2xl">
              <FileCode className="h-6 w-6 text-primary" />
              llm.txt Generator
            </DialogTitle>
            <DialogDescription>
              Generated llm.txt file to help AI crawlers better understand your website
            </DialogDescription>
          </DialogHeader>

          <div className="space-y-4 mt-4">
            {/* Info Banner */}
            <div className="p-4 bg-info/10 border border-info/20 rounded-lg">
              <div className="flex gap-3">
                <AlertTriangle className="h-5 w-5 text-info mt-0.5 flex-shrink-0" />
                <div>
                  <p className="font-medium text-info mb-1">What is llm.txt?</p>
                  <p className="text-sm text-muted-foreground">
                    llm.txt is a file (similar to robots.txt) that helps AI models like ChatGPT, Claude, 
                    and Gemini better understand and represent your website content. Place it in your 
                    website root directory to improve how LLMs cite and reference your products.
                  </p>
                </div>
              </div>
            </div>

            {/* Preview */}
            <div>
              <Label className="text-sm font-semibold mb-2 block">Generated llm.txt Content:</Label>
              <Textarea
                value={llmTextContent}
                readOnly
                className="font-mono text-xs h-[400px] bg-muted/50"
              />
            </div>

            {/* How to Use */}
            <div className="p-4 bg-gradient-to-r from-purple-50 to-pink-50 dark:from-purple-950/20 dark:to-pink-950/20 border border-purple-200 dark:border-purple-800 rounded-lg">
              <h4 className="font-semibold mb-3 flex items-center gap-2">
                <CheckCircle className="h-4 w-4 text-success" />
                How to Use This File:
              </h4>
              <ol className="space-y-2 text-sm">
                <li className="flex gap-2">
                  <span className="font-bold text-primary">1.</span>
                  <span>Download the llm.txt file using the button below</span>
                </li>
                <li className="flex gap-2">
                  <span className="font-bold text-primary">2.</span>
                  <span>Upload it to your website's root directory (e.g., yoursite.com/llm.txt)</span>
                </li>
                <li className="flex gap-2">
                  <span className="font-bold text-primary">3.</span>
                  <span>Verify it's accessible by visiting: {profile?.websiteUrl}/llm.txt</span>
                </li>
                <li className="flex gap-2">
                  <span className="font-bold text-primary">4.</span>
                  <span>Update it monthly to keep AI models informed about your latest content</span>
                </li>
              </ol>
            </div>

            {/* Benefits */}
            <div>
              <h4 className="font-semibold mb-3">Benefits:</h4>
              <div className="grid grid-cols-1 md:grid-cols-2 gap-3">
                <div className="flex gap-2 text-sm">
                  <CheckCircle className="h-4 w-4 text-success mt-0.5 flex-shrink-0" />
                  <span>Helps LLMs accurately cite your products</span>
                </div>
                <div className="flex gap-2 text-sm">
                  <CheckCircle className="h-4 w-4 text-success mt-0.5 flex-shrink-0" />
                  <span>Improves AI model understanding of your content</span>
                </div>
                <div className="flex gap-2 text-sm">
                  <CheckCircle className="h-4 w-4 text-success mt-0.5 flex-shrink-0" />
                  <span>Prioritizes your most important pages</span>
                </div>
                <div className="flex gap-2 text-sm">
                  <CheckCircle className="h-4 w-4 text-success mt-0.5 flex-shrink-0" />
                  <span>Boosts visibility in AI-powered searches</span>
                </div>
              </div>
            </div>

            {/* Actions */}
            <div className="flex gap-3">
              <Button
                onClick={handleDownloadLLMText}
                className="flex-1 gap-2"
              >
                <Download className="h-4 w-4" />
                Download llm.txt
              </Button>
              <Button
                onClick={handleCopyLLMText}
                variant="outline"
                className="flex-1 gap-2"
              >
                <Copy className="h-4 w-4" />
                Copy to Clipboard
              </Button>
            </div>

            <Button
              onClick={() => setShowLLMTextModal(false)}
              variant="outline"
              className="w-full"
            >
              Close
            </Button>
          </div>
        </DialogContent>
      </Dialog>

      {/* SEO Health Check Modal */}
      <Dialog open={showHealthModal} onOpenChange={setShowHealthModal}>
        <DialogContent className="max-w-3xl max-h-[80vh] overflow-y-auto">
          <DialogHeader>
            <DialogTitle className="flex items-center gap-2 text-2xl">
              <Activity className="h-6 w-6 text-primary" />
              SEO Health Check Results
            </DialogTitle>
            <DialogDescription>
              Comprehensive analysis of your website's SEO health
            </DialogDescription>
          </DialogHeader>

          <div className="space-y-6 mt-4">
            {healthCheckData ? (
              <>
            {/* Overall Health Score */}
            <div className={`p-6 bg-gradient-to-r rounded-lg border ${
              healthCheckData.overallScore >= 80 
                ? 'from-success/10 to-success/5 border-success/20' 
                : healthCheckData.overallScore >= 60 
                ? 'from-warning/10 to-warning/5 border-warning/20'
                : 'from-destructive/10 to-destructive/5 border-destructive/20'
            }`}>
              <div className="flex items-center justify-between mb-4">
                <div>
                  <h3 className="text-lg font-semibold">Overall SEO Health</h3>
                  <p className="text-sm text-muted-foreground">Based on real-time analysis</p>
                </div>
                <div className="text-center">
                  <p className={`text-4xl font-bold ${
                    healthCheckData.overallScore >= 80 
                      ? 'text-success' 
                      : healthCheckData.overallScore >= 60 
                      ? 'text-warning'
                      : 'text-destructive'
                  }`}>{healthCheckData.overallScore}/100</p>
                  <Badge className={`mt-2 ${
                    healthCheckData.overallScore >= 80 
                      ? 'bg-success text-white' 
                      : healthCheckData.overallScore >= 60 
                      ? 'bg-warning text-white'
                      : 'bg-destructive text-white'
                  }`}>
                    {healthCheckData.overallScore >= 80 ? 'Excellent' : healthCheckData.overallScore >= 60 ? 'Good' : 'Needs Work'}
                  </Badge>
                </div>
              </div>
              <Progress value={healthCheckData.overallScore} className="h-2" />
            </div>

            {/* Health Categories */}
            <div className="grid gap-4">
              {/* Technical SEO */}
              <div className="p-4 border rounded-lg">
                <div className="flex items-center justify-between mb-2">
                  <div className="flex items-center gap-2">
                    {healthCheckData.categories.technicalSeo.score >= 75 ? (
                      <CheckCircle className="h-5 w-5 text-success" />
                    ) : healthCheckData.categories.technicalSeo.score >= 50 ? (
                      <AlertTriangle className="h-5 w-5 text-warning" />
                    ) : (
                      <XCircle className="h-5 w-5 text-destructive" />
                    )}
                    <span className="font-medium">Technical SEO</span>
                  </div>
                  <Badge variant="outline" className={
                    healthCheckData.categories.technicalSeo.score >= 75 
                      ? 'bg-success/10 text-success' 
                      : healthCheckData.categories.technicalSeo.score >= 50
                      ? 'bg-warning/10 text-warning'
                      : 'bg-destructive/10 text-destructive'
                  }>
                    {healthCheckData.categories.technicalSeo.score}/100
                  </Badge>
                </div>
                <p className="text-sm text-muted-foreground">
                  {healthCheckData.categories.technicalSeo.issues.length > 0 
                    ? healthCheckData.categories.technicalSeo.issues.join(', ')
                    : 'All technical SEO factors are optimal'}
                </p>
              </div>

              {/* On-Page SEO */}
              <div className="p-4 border rounded-lg">
                <div className="flex items-center justify-between mb-2">
                  <div className="flex items-center gap-2">
                    {healthCheckData.categories.onPageSeo.score >= 75 ? (
                      <CheckCircle className="h-5 w-5 text-success" />
                    ) : healthCheckData.categories.onPageSeo.score >= 50 ? (
                      <AlertTriangle className="h-5 w-5 text-warning" />
                    ) : (
                      <XCircle className="h-5 w-5 text-destructive" />
                    )}
                    <span className="font-medium">On-Page SEO</span>
                  </div>
                  <Badge variant="outline" className={
                    healthCheckData.categories.onPageSeo.score >= 75 
                      ? 'bg-success/10 text-success' 
                      : healthCheckData.categories.onPageSeo.score >= 50
                      ? 'bg-warning/10 text-warning'
                      : 'bg-destructive/10 text-destructive'
                  }>
                    {healthCheckData.categories.onPageSeo.score}/100
                  </Badge>
                </div>
                <p className="text-sm text-muted-foreground">
                  {healthCheckData.categories.onPageSeo.issues.length > 0 
                    ? healthCheckData.categories.onPageSeo.issues.join(', ')
                    : 'Meta tags, headers, and content are well-optimized'}
                </p>
              </div>

              {/* Content Quality */}
              <div className="p-4 border rounded-lg">
                <div className="flex items-center justify-between mb-2">
                  <div className="flex items-center gap-2">
                    {healthCheckData.categories.contentQuality.score >= 75 ? (
                      <CheckCircle className="h-5 w-5 text-success" />
                    ) : healthCheckData.categories.contentQuality.score >= 50 ? (
                      <AlertTriangle className="h-5 w-5 text-warning" />
                    ) : (
                      <XCircle className="h-5 w-5 text-destructive" />
                    )}
                    <span className="font-medium">Content Quality</span>
                  </div>
                  <Badge variant="outline" className={
                    healthCheckData.categories.contentQuality.score >= 75 
                      ? 'bg-success/10 text-success' 
                      : healthCheckData.categories.contentQuality.score >= 50
                      ? 'bg-warning/10 text-warning'
                      : 'bg-destructive/10 text-destructive'
                  }>
                    {healthCheckData.categories.contentQuality.score}/100
                  </Badge>
                </div>
                <p className="text-sm text-muted-foreground">
                  {healthCheckData.categories.contentQuality.issues.length > 0 
                    ? healthCheckData.categories.contentQuality.issues.join(', ')
                    : 'Content quality and structure are excellent'}
                </p>
              </div>

              {/* Performance */}
              <div className="p-4 border rounded-lg">
                <div className="flex items-center justify-between mb-2">
                  <div className="flex items-center gap-2">
                    {healthCheckData.categories.performance.score >= 75 ? (
                      <CheckCircle className="h-5 w-5 text-success" />
                    ) : healthCheckData.categories.performance.score >= 50 ? (
                      <AlertTriangle className="h-5 w-5 text-warning" />
                    ) : (
                      <XCircle className="h-5 w-5 text-destructive" />
                    )}
                    <span className="font-medium">Performance</span>
                  </div>
                  <Badge variant="outline" className={
                    healthCheckData.categories.performance.score >= 75 
                      ? 'bg-success/10 text-success' 
                      : healthCheckData.categories.performance.score >= 50
                      ? 'bg-warning/10 text-warning'
                      : 'bg-destructive/10 text-destructive'
                  }>
                    {healthCheckData.categories.performance.score}/100
                  </Badge>
                </div>
                <p className="text-sm text-muted-foreground">
                  {healthCheckData.categories.performance.issues.length > 0 
                    ? healthCheckData.categories.performance.issues.join(', ')
                    : 'Page speed and performance are optimal'}
                </p>
              </div>

              {/* Security */}
              <div className="p-4 border rounded-lg">
                <div className="flex items-center justify-between mb-2">
                  <div className="flex items-center gap-2">
                    {healthCheckData.categories.security.score >= 75 ? (
                      <CheckCircle className="h-5 w-5 text-success" />
                    ) : healthCheckData.categories.security.score >= 50 ? (
                      <AlertTriangle className="h-5 w-5 text-warning" />
                    ) : (
                      <XCircle className="h-5 w-5 text-destructive" />
                    )}
                    <span className="font-medium">Security</span>
                  </div>
                  <Badge variant="outline" className={
                    healthCheckData.categories.security.score >= 75 
                      ? 'bg-success/10 text-success' 
                      : healthCheckData.categories.security.score >= 50
                      ? 'bg-warning/10 text-warning'
                      : 'bg-destructive/10 text-destructive'
                  }>
                    {healthCheckData.categories.security.score}/100
                  </Badge>
                </div>
                <p className="text-sm text-muted-foreground">
                  {healthCheckData.categories.security.issues.length > 0 
                    ? healthCheckData.categories.security.issues.join(', ')
                    : 'Security headers and HTTPS are properly configured'}
                </p>
              </div>
            </div>

            {/* Action Items */}
            {healthCheckData.actionItems && healthCheckData.actionItems.length > 0 && (
              <div>
                <h3 className="text-lg font-semibold mb-4">Priority Action Items</h3>
                <div className="space-y-2">
                  {healthCheckData.actionItems.map((item: any, index: number) => (
                    <div 
                      key={index}
                      className={`flex gap-3 p-3 rounded-lg border ${
                        item.priority === 'critical' || item.priority === 'high'
                          ? 'bg-destructive/5 border-destructive/20'
                          : item.priority === 'medium'
                          ? 'bg-warning/5 border-warning/20'
                          : 'bg-info/5 border-info/20'
                      }`}
                    >
                      <span className={`font-bold ${
                        item.priority === 'critical' || item.priority === 'high'
                          ? 'text-destructive'
                          : item.priority === 'medium'
                          ? 'text-warning'
                          : 'text-info'
                      }`}>{index + 1}.</span>
                      <div>
                        <p className="font-medium">{item.title}</p>
                        <p className="text-sm text-muted-foreground">{item.description}</p>
                      </div>
                    </div>
                  ))}
                </div>
              </div>
            )}

            <Button onClick={() => setShowHealthModal(false)} className="w-full">
              Close
            </Button>
              </>
            ) : (
              <div className="text-center py-8">
                <p className="text-muted-foreground">Loading health check data...</p>
              </div>
            )}
          </div>
        </DialogContent>
      </Dialog>

      {/* Content Optimizer Modal - Enhanced with full details */}
      <Dialog open={showOptimizeModal} onOpenChange={setShowOptimizeModal}>
        <DialogContent className="max-w-4xl max-h-[85vh] overflow-y-auto">
          <DialogHeader>
            <DialogTitle className="flex items-center gap-2 text-2xl">
              <Wand2 className="h-6 w-6 text-primary" />
              Content Optimization Recommendations
            </DialogTitle>
            <DialogDescription>
              Comprehensive AI-powered analysis to maximize your AEO visibility
            </DialogDescription>
          </DialogHeader>

          <div className="space-y-6 mt-4">
            {optimizationData && Array.isArray(optimizationData) ? (
              <>
            {/* Summary Card */}
            <div className="p-6 bg-gradient-to-r from-primary/10 via-primary/5 to-transparent rounded-lg border border-primary/20">
              <div className="flex items-start justify-between mb-4">
                <div className="flex-1">
                  <h3 className="text-xl font-bold mb-2 flex items-center gap-2">
                    <TrendingUp className="h-5 w-5 text-primary" />
                    AI-Powered Optimization Analysis
                  </h3>
                  <p className="text-muted-foreground text-sm">
                    Based on analysis of your content and current visibility, we've identified {optimizationData.length} key opportunities to improve 
                    your AEO performance and citation weight.
                  </p>
                </div>
              </div>
            </div>

            {/* Detailed Recommendations */}
            <div>
              <h3 className="text-lg font-semibold mb-4">Detailed Recommendations</h3>
              <div className="space-y-4">
                {optimizationData.map((rec: any, idx: number) => {
                  const getPriorityColor = (priority: string) => {
                    switch (priority?.toLowerCase()) {
                      case 'critical': return 'bg-destructive text-white';
                      case 'high': return 'bg-primary text-primary-foreground';
                      case 'medium': return 'bg-warning text-white';
                      default: return 'bg-muted text-foreground';
                    }
                  };

                  const getImpactColor = (impact: string) => {
                    switch (impact?.toLowerCase()) {
                      case 'high': return 'bg-destructive text-white';
                      case 'medium': return 'bg-warning text-white';
                      default: return 'bg-info text-white';
                    }
                  };

                  return (
                  <motion.div
                    key={idx}
                    initial={{ opacity: 0, x: -20 }}
                    animate={{ opacity: 1, x: 0 }}
                    transition={{ delay: idx * 0.1 }}
                  >
                    <Card className="p-6 hover:shadow-lg transition-shadow">
                      <div className="flex items-start gap-4">
                        <div className="flex-1">
                          <div className="flex items-start justify-between mb-3">
                            <h4 className="font-bold text-lg">{rec.title}</h4>
                            <div className="flex gap-2">
                              <Badge className={`${getPriorityColor(rec.priority)} text-xs`}>
                                {rec.priority}
                              </Badge>
                              <Badge className={`${getImpactColor(rec.impact)} text-xs`}>
                                {rec.impact?.toUpperCase()} IMPACT
                              </Badge>
                            </div>
                          </div>
                          <p className="text-muted-foreground mb-4 text-sm leading-relaxed">
                            {rec.description}
                          </p>
                          
                          <div className="grid grid-cols-3 gap-4 mb-4 p-3 bg-muted/30 rounded-lg">
                            <div>
                              <p className="text-xs text-muted-foreground mb-1">Difficulty</p>
                              <p className="font-semibold capitalize">{rec.difficulty}</p>
                            </div>
                            <div>
                              <p className="text-xs text-muted-foreground mb-1">Expected Gain</p>
                              <p className="font-semibold text-primary">{rec.improvement}</p>
                            </div>
                            <div>
                              <p className="text-xs text-muted-foreground mb-1">Category</p>
                              <p className="font-semibold capitalize">{rec.category}</p>
                            </div>
                          </div>

                          {rec.actionItems && rec.actionItems.length > 0 && (
                            <div className="border-t pt-3">
                              <p className="text-sm font-semibold mb-2 flex items-center gap-2">
                                <CheckCircle className="h-4 w-4 text-primary" />
                                Action Items:
                              </p>
                              <ul className="space-y-2">
                                {rec.actionItems.map((item: string, i: number) => (
                                  <li key={i} className="text-sm text-muted-foreground flex items-start gap-2">
                                    <span className="text-primary mt-0.5 font-bold">•</span>
                                    <span>{item}</span>
                                  </li>
                                ))}
                              </ul>
                            </div>
                          )}
                        </div>
                      </div>
                    </Card>
                  </motion.div>
                  );
                })}
              </div>
            </div>

            <Button onClick={() => setShowOptimizeModal(false)} className="w-full">
              Close
            </Button>
              </>
            ) : (
              <div className="text-center py-8">
                <p className="text-muted-foreground">Loading optimization recommendations...</p>
              </div>
            )}
          </div>
        </DialogContent>
      </Dialog>
    </>
  );
};
